### ISSUE TITLE
Stream request errors with Azure OpenAI API version 2023-06-01-preview and later

### ISSUE THREAD

**Issue by material3dge** [RetellAI/python-backend-demo#5]
**Describe the bug**
After specifying Azure OpenAI API version 2023-06-01-preview or later for stream requests, an error occurs due to an unexpected empty choices array in the stream response. This issue is specific to Azure OpenAI and relates to the inclusion of responsible AI content filtering results in responses from this version onward.

**Offending code:**

>        for chunk in stream:
>             # Step 3: Extract the functions
>             if chunk.choices[0].delta.tool_calls:
>                 tool_calls = chunk.choices[0].delta.tool_calls[0]
>                 if tool_calls.id:
>                     if func_call:
>                         # Another function received, old function complete, can break here.
>                         break
>                     func_call = {
>                         "id": tool_calls.id,
>                         "func_name": tool_calls.function.name or "",
>                         "arguments": {},
>                     }
>                 else:
>                     # append argument
>                     func_arguments += tool_calls.function.arguments or ""

**Suggested resolution:**
Check length of choices property during chunk processing

>        for chunk in stream:
>             if len(chunk.choices) == 0:
>                 continue
>             # Step 3: Extract the functions
>             if chunk.choices[0].delta.tool_calls:
>                 tool_calls = chunk.choices[0].delta.tool_calls[0]
>                 if tool_calls.id:
>                     if func_call:
>                         # Another function received, old function complete, can break here.
>                         break
>                     func_call = {
>                         "id": tool_calls.id,
>                         "func_name": tool_calls.function.name or "",
>                         "arguments": {},
>                     }
>                 else:
>                     # append argument
>                     func_arguments += tool_calls.function.arguments or ""

**Expected behavior**
When sending stream requests with Azure OpenAI, it is expected that no IndexError occurs and the response is successfully retrieved.

**Additional context**
This issue appears to stem from a change in the API response format introduced with the 2023-06-01-preview version of Azure OpenAI. This version includes responsible AI content filtering results in the responses, leading to an initial empty choices array in the stream response, which contradicts the implicit assumption the existing llm.py and llm_with_func_calling.py code that choices length is always one or more. The relevant API change is documented https://github.com/Azure/azure-rest-api-specs/pull/25880.

**Comment by AustinZzx** [comment]
Nice catch, we will add an azure openai llm implementation with the fix mentioned here.
