### ISSUE TITLE
Failing with "ended 1002 Invalid URL"

### ISSUE THREAD

**Issue by nickvelloff** [RetellAI/python-backend-demo#8]
I have Dockerized and deployed a demo to EC-2. 

Client is running on http://3.133.138.179:3000
Server is running on http://3.133.138.179:8080

Console log
```
Audio worklet starting
retell-client-js-sdk.js?v=8e624e71:334 Audio worklet loaded
retell-client-js-sdk.js?v=8e624e71:334 Audio worklet setup
App.tsx:170 started
App.tsx:190 ended 1002 Invalid URL
```
http://3.133.138.179:8080/update-agent 200 success
http://3.133.138.179:8080/register-call 200 success

Any ideas why I'm getting `App.tsx:190 ended 1002 Invalid URL`?

**Comment by nickvelloff** [comment]
Figured it out...

**Comment by weijia-yu** [comment]
@nickvelloff  Glad that you figured that out! What was the root cause?

**Comment by nickvelloff** [comment]
@weijia-yu Silly mistake, when I updated the agent socket URL it didn't contain the port.
